version: 1.2.1.{build}
image: Visual Studio 2019

environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

    GITHUB_API_TOKEN:
        secure: A6oZzdRaFi7zWLB8d5/gDfxtzn4Zh71cmGgmgA+FNySDrrZiLUJYcc+lclUa3F2y

build_script:
- ps: >-
    dotnet --info

    dotnet restore

    dotnet run -c Release -p ./tests/Wox.Plugin.Github.Tests.fsproj -- --summary --colours 0

    dotnet pack -c Release

after_build:
- ps: >-
    Compress-Archive -Path "src\bin\Release\net462\*" -DestinationPath "plugin.zip"

    Rename-Item plugin.zip Wox.Plugin.Github.wox

artifacts:
    - path: 'src\bin\Release\*.nupkg'
    - path: '*.wox'