version: 1.3.1.{build}
image: Visual Studio 2022

environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

    GITHUB_API_TOKEN:
        secure: saOmp9u7Yu7HRg2TONypwKZk02hBM+kvu0DDTF76AzXFtwT6P79u+ClCG+VHOIQKZFm/6wNEt+Jx2xyR1+Oij60h/rzjGSbCJc7Jj8Vy2FBbCkfw1bSwrlz5VvRdSFHi

before_build:
    - ps: dotnet --info
    - ps: dotnet restore

build_script:
    - ps: dotnet pack -c Release

after_build:
- ps: >-
    $zipSettings = @{
        Path = Get-ChildItem -Path ".\src\bin\Release\*" -Exclude "*.nupkg"
        DestinationPath = "Flow.Plugin.Github.zip"
    }

    Compress-Archive @zipSettings

test_script:
    - ps: dotnet run --no-build -c Release --project ./tests/Flow.Plugin.Github.Tests.fsproj -- --summary

artifacts:
    - path: 'src\bin\Release\*.nupkg'
    - path: '*.zip'
