version: 1.2.0.{build}
image: Visual Studio 2019

environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

build_script:
- ps: >-
    dotnet --info

    dotnet restore

    dotnet run -c Release -p ./tests/Wox.Plugin.Github.Tests.fsproj -- --summary --colours 0

    dotnet pack -c Release

after_build:
- ps: >-
    Compress-Archive -Path "Wox.Plugin.Github\bin\Release\net462\*" -DestinationPath "plugin.zip"

    Rename-Item plugin.zip Wox.Plugin.Github.wox

artifacts:
    - path: 'Wox.Plugin.Github\bin\Release\*.nupkg'
    - path: '*.wox'